'use strict';

function renderSettings(){const p=activeProject();return`<div class="page"><div class="page-title"><div><h1>我的创作空间</h1><p>隐私、备份、作品管理与安装说明</p></div></div><section class="hero"><h1>${esc(p.title)}</h1><p>当前资料保存在 Safari / 主屏幕 App 的 IndexedDB 中，不会随网页代码提交到 GitHub。</p><div class="hero-row"><button class="primary" data-action="export">导出备份</button><button class="secondary" data-action="import">导入</button></div></section><div class="section-head"><h2>作品</h2></div><div class="card setting-list"><button class="setting-row" data-action="projects"><i>▤</i><div><b>切换或新建作品</b><small>${state.projects.length} 个本地作品</small></div><span class="chev">›</span></button><button class="setting-row" data-action="rename-project"><i>✎</i><div><b>修改作品名称</b><small>标题、说明与封面字</small></div><span class="chev">›</span></button></div><div class="section-head"><h2>隐私与安全</h2></div><div class="card setting-list"><button class="setting-row" data-action="pin"><i>⌾</i><div><b>${state.settings.pinHash?'修改 / 关闭应用锁':'设置应用锁'}</b><small>打开时需要输入本机 PIN</small></div><span class="chev">›</span></button><button class="setting-row" data-action="export-encrypted"><i>◇</i><div><b>导出加密备份</b><small>AES-GCM 加密后保存到文件</small></div><span class="chev">›</span></button><button class="setting-row" data-action="privacy-info"><i>◉</i><div><b>数据保存说明</b><small>了解 GitHub 网页与本机资料的区别</small></div><span class="chev">›</span></button></div><div class="section-head"><h2>使用</h2></div><div class="card setting-list"><button class="setting-row" data-action="install-help"><i>□</i><div><b>添加到 iPhone 主屏幕</b><small>像 App 一样全屏打开</small></div><span class="chev">›</span></button><button class="setting-row" data-action="clear-data"><i>⌫</i><div><b>清空当前作品</b><small>此操作不可撤销，请先导出</small></div><span class="chev">›</span></button></div></div>`;}

function newManuscript(item=null){if(!item){const rec={id:uid(),title:'未命名章节',chapter:'',content:'',createdAt:nowISO(),updatedAt:nowISO()};activeProject().modules.manuscripts.unshift(rec);save();currentItem=rec.id;}else currentItem=item.id;currentModule='manuscripts';route='editor';render();}
function renderEditor(id){const item=activeProject().modules.manuscripts.find(x=>x.id===id);if(!item){route='writing';return renderWritingHub();}return`<div class="page"><div class="page-title"><button class="back-btn" data-route="writing">‹</button><div><h1>正文编辑</h1><p>自动保存到本机</p></div><button class="tiny-btn" data-action="delete-manuscript">删除</button></div><div class="editor-shell"><div class="editor-meta"><input id="msTitle" value="${esc(item.title)}" placeholder="章节标题"><input id="msChapter" value="${esc(item.chapter||'')}" placeholder="章序"></div><textarea class="editor" id="msContent" placeholder="从一个画面、一句话或一个冲突开始……">${esc(item.content||'')}</textarea><div class="editor-foot"><span id="saveStatus">已保存</span><span id="wordStatus">${wordCount(item.content)} 字</span></div></div></div>`;}
function bindEditor(){const item=activeProject().modules.manuscripts.find(x=>x.id===currentItem);if(!item)return;let timer;const sync=()=>{item.title=$('#msTitle').value||'未命名章节';item.chapter=$('#msChapter').value;item.content=$('#msContent').value;item.updatedAt=nowISO();$('#wordStatus').textContent=wordCount(item.content)+' 字';$('#saveStatus').textContent='保存中…';clearTimeout(timer);timer=setTimeout(()=>{save();$('#saveStatus').textContent='已保存';},250);};['msTitle','msChapter','msContent'].forEach(id=>$(`#${id}`).addEventListener('input',sync));}

function renderLock(){document.querySelector('#app').innerHTML=`<div class="lock-screen"><div class="lock-card"><div class="lock-logo">世</div><h1>世界观工坊</h1><p style="color:var(--muted)">输入本机 PIN 解锁私人创作空间</p><input id="unlockPin" type="password" inputmode="numeric" maxlength="12" placeholder="••••"><button class="primary" id="unlockBtn">解锁</button></div></div>`;$('#unlockBtn').onclick=async()=>{const h=await hashText($('#unlockPin').value);if(h===state.settings.pinHash){unlocked=true;render();}else toast('PIN 不正确');};}
async function hashText(t){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');}
