'use strict';

const commonFields={
  title:{key:'title',label:'名称 / 标题',type:'text',required:true,placeholder:'输入名称'},
  alias:{key:'alias',label:'别名 / 称号',type:'text',placeholder:'可填写多个，用顿号分隔'},
  summary:{key:'summary',label:'一句话概述',type:'text',placeholder:'快速说明它是什么'},
  tags:{key:'tags',label:'标签',type:'tags',placeholder:'输入后按回车'},
  image:{key:'image',label:'形象 / 封面',type:'image'},
  notes:{key:'notes',label:'补充备注',type:'textarea',placeholder:'任何尚未归类的灵感、禁忌或待确认内容'}
};

const MODULES=[
 {key:'characters',name:'角色库',icon:'♙',desc:'人物身份、性格、欲望、秘密与成长弧',fields:[commonFields.title,commonFields.alias,commonFields.image,{key:'role',label:'叙事身份',type:'select',options:['主角','重要配角','反派','群像角色','历史人物','路人 / 临时角色']},{key:'species',label:'种族 / 族群',type:'text'},{key:'gender',label:'性别 / 自我认同',type:'text'},{key:'age',label:'年龄 / 生辰',type:'text'},{key:'occupation',label:'职业 / 身份',type:'text'},{key:'location',label:'出生地 / 常驻地',type:'text'},{key:'personality',label:'性格关键词',type:'textarea'},{key:'desire',label:'核心欲望',type:'textarea'},{key:'fear',label:'恐惧与弱点',type:'textarea'},{key:'motivation',label:'行动动机',type:'textarea'},{key:'secret',label:'秘密 / 隐瞒',type:'textarea'},{key:'arc',label:'角色弧线',type:'textarea'},{key:'voice',label:'说话方式 / 口头禅',type:'textarea'},commonFields.tags,commonFields.notes]},
 {key:'appearance',name:'形象',icon:'◈',desc:'外貌、服装、色板、表情与视觉参考',fields:[commonFields.title,{key:'owner',label:'所属角色 / 族群',type:'text'},commonFields.image,{key:'body',label:'体态与轮廓',type:'textarea'},{key:'face',label:'五官与辨识点',type:'textarea'},{key:'hair',label:'发型 / 毛发',type:'textarea'},{key:'eyes',label:'眼睛 / 神态',type:'textarea'},{key:'clothes',label:'服装系统',type:'textarea'},{key:'accessories',label:'配饰 / 武器',type:'textarea'},{key:'palette',label:'主色板',type:'text',placeholder:'#色值或颜色名称'},{key:'expressions',label:'常见表情与姿态',type:'textarea'},{key:'changes',label:'不同阶段的形象变化',type:'textarea'},commonFields.tags,commonFields.notes]},
 {key:'relationships',name:'关系',icon:'↔',desc:'人物、组织、地点之间的双向关联',fields:[commonFields.title,{key:'source',label:'关系起点',type:'text',required:true},{key:'target',label:'关系终点',type:'text',required:true},{key:'relation',label:'关系类型',type:'select',options:['亲属','朋友','恋人','盟友','上下级','师徒','宿敌','仇敌','利用','守护','债务','秘密关联','其他']},{key:'direction',label:'方向',type:'select',options:['双向','起点 → 终点','终点 → 起点']},{key:'strength',label:'关系强度 1–10',type:'number',min:1,max:10},{key:'publicFace',label:'表面关系',type:'textarea'},{key:'truth',label:'真实关系',type:'textarea'},{key:'turning',label:'关系转折点',type:'textarea'},{key:'status',label:'当前状态',type:'select',options:['稳定','升温','恶化','断裂','未知','已结束']},commonFields.tags,commonFields.notes]},
 {key:'organizations',name:'组织',icon:'⌂',desc:'国家、家族、宗门、公司、军团与秘密结社',fields:[commonFields.title,commonFields.alias,commonFields.image,{key:'type',label:'组织类型',type:'text'},{key:'founding',label:'成立时间 / 起源',type:'text'},{key:'hq',label:'总部 / 势力范围',type:'text'},{key:'leader',label:'领袖与核心人物',type:'textarea'},{key:'members',label:'成员结构与阶级',type:'textarea'},{key:'goal',label:'公开目标',type:'textarea'},{key:'hiddenGoal',label:'隐藏目的',type:'textarea'},{key:'resources',label:'资源与优势',type:'textarea'},{key:'rules',label:'制度、戒律、入会规则',type:'textarea'},{key:'symbol',label:'标志、制服、口号',type:'textarea'},{key:'relations',label:'盟友与敌对组织',type:'textarea'},{key:'riseFall',label:'兴衰历程',type:'textarea'},commonFields.tags,commonFields.notes]},
 {key:'characterJourney',name:'角色历程',icon:'⌁',desc:'按时间记录人物经历、伤痕、选择与变化',timeline:true,fields:[commonFields.title,{key:'character',label:'角色',type:'text',required:true},{key:'date',label:'世界内日期 / 阶段',type:'text'},{key:'order',label:'排序数字',type:'number'},{key:'place',label:'发生地点',type:'text'},{key:'event',label:'经历事件',type:'textarea',required:true},{key:'choice',label:'角色选择',type:'textarea'},{key:'gainLoss',label:'获得与失去',type:'textarea'},{key:'change',label:'心理 / 能力变化',type:'textarea'},{key:'links',label:'关联人物、物品、剧情',type:'textarea'},commonFields.tags,commonFields.notes]},
 {key:'worldPlot',name:'世界剧情',icon:'✦',desc:'世界历史、纪元、灾难、战争与共同记忆',timeline:true,fields:[commonFields.title,{key:'era',label:'纪元 / 年代',type:'text'},{key:'order',label:'排序数字',type:'number'},{key:'scope',label:'影响范围',type:'text'},{key:'cause',label:'起因',type:'textarea'},{key:'process',label:'经过',type:'textarea'},{key:'result',label:'结果',type:'textarea'},{key:'winners',label:'受益者',type:'textarea'},{key:'losers',label:'受损者',type:'textarea'},{key:'legacy',label:'遗留影响 / 后世解释',type:'textarea'},commonFields.tags,commonFields.notes]},
 {key:'mapCenter',name:'地图中心',icon:'⌖',desc:'插入地形、城市、道路、标记与地图底图',special:'map',fields:[]},
 {key:'worldRules',name:'世界运行',icon:'⚙',desc:'自然法则、社会机制、因果边界与限制',fields:[commonFields.title,{key:'category',label:'规则类别',type:'select',options:['自然法则','超自然法则','政治机制','社会机制','生死机制','信息传播','空间规则','时间规则','其他']},{key:'rule',label:'规则正文',type:'textarea',required:true},{key:'why',label:'形成原因',type:'textarea'},{key:'cost',label:'代价 / 限制',type:'textarea'},{key:'exceptions',label:'例外情况',type:'textarea'},{key:'consequence',label:'违反后果',type:'textarea'},{key:'evidence',label:'剧情中的体现',type:'textarea'},commonFields.tags,commonFields.notes]},
 {key:'worldBible',name:'世界总纲',icon:'▤',desc:'主题、类型、基调、矛盾与核心设定总览',fields:[commonFields.title,commonFields.image,{key:'genre',label:'题材 / 类型',type:'text'},{key:'tone',label:'气质 / 基调',type:'text'},{key:'theme',label:'核心主题',type:'textarea'},{key:'premise',label:'世界前提',type:'textarea'},{key:'centralConflict',label:'核心矛盾',type:'textarea'},{key:'ordinaryLife',label:'普通人的日常',type:'textarea'},{key:'unique',label:'与现实最大的不同',type:'textarea'},{key:'redLines',label:'不可推翻的底层设定',type:'textarea'},{key:'openQuestions',label:'待回答问题',type:'textarea'},commonFields.tags,commonFields.notes]},
 {key:'powerSystem',name:'力量体系',icon:'✧',desc:'能力来源、等级、代价、克制与成长方式',fields:[commonFields.title,commonFields.image,{key:'source',label:'力量来源',type:'textarea'},{key:'users',label:'使用者资格',type:'textarea'},{key:'activation',label:'发动条件',type:'textarea'},{key:'levels',label:'等级 / 阶段',type:'textarea'},{key:'abilities',label:'典型能力',type:'textarea'},{key:'cost',label:'消耗与代价',type:'textarea'},{key:'limits',label:'限制 / 禁忌',type:'textarea'},{key:'counter',label:'克制与破解',type:'textarea'},{key:'training',label:'训练与升级',type:'textarea'},{key:'socialImpact',label:'对社会的影响',type:'textarea'},commonFields.tags,commonFields.notes]},
 {key:'nature',name:'自然图鉴',icon:'❦',desc:'动物、植物、矿物、怪物、气候与生态链',fields:[commonFields.title,commonFields.image,{key:'kind',label:'类别',type:'select',options:['动物','植物','真菌','矿物','怪物','微生物','天气现象','生态系统','其他']},{key:'habitat',label:'栖息地 / 分布',type:'text'},{key:'appearance',label:'形态特征',type:'textarea'},{key:'behavior',label:'习性 / 生长规律',type:'textarea'},{key:'diet',label:'食性 / 能量来源',type:'textarea'},{key:'lifeCycle',label:'生命周期',type:'textarea'},{key:'ecology',label:'生态位与天敌',type:'textarea'},{key:'uses',label:'用途 / 价值',type:'textarea'},{key:'danger',label:'危险性',type:'textarea'},{key:'symbolism',label:'文化象征',type:'textarea'},commonFields.tags,commonFields.notes]},
 {key:'economy',name:'经济与货币',icon:'¤',desc:'货币、贸易、税收、产业、阶级与生存成本',fields:[commonFields.title,commonFields.image,{key:'type',label:'条目类型',type:'select',options:['货币','产业','贸易路线','商品','税制','金融机构','经济危机','阶级收入','其他']},{key:'issuer',label:'发行 / 控制者',type:'text'},{key:'value',label:'价值与换算',type:'textarea'},{key:'materials',label:'材质 / 生产方式',type:'textarea'},{key:'circulation',label:'流通范围',type:'textarea'},{key:'prices',label:'典型物价',type:'textarea'},{key:'trade',label:'进出口与稀缺资源',type:'textarea'},{key:'tax',label:'税收 / 贡赋',type:'textarea'},{key:'blackMarket',label:'地下经济',type:'textarea'},{key:'impact',label:'对阶级与剧情的影响',type:'textarea'},commonFields.tags,commonFields.notes]},
 {key:'soulFaith',name:'灵魂与信仰',icon:'☾',desc:'神祇、宗教、灵魂、生死、仪式与异端',fields:[commonFields.title,commonFields.image,{key:'type',label:'类别',type:'select',options:['宗教','神祇','灵魂规则','死后世界','仪式','圣地','教派','异端','神话','其他']},{key:'origin',label:'起源 / 神话',type:'textarea'},{key:'belief',label:'核心教义',type:'textarea'},{key:'soul',label:'灵魂构成与归宿',type:'textarea'},{key:'rituals',label:'仪式与节日',type:'textarea'},{key:'clergy',label:'神职与组织',type:'textarea'},{key:'taboo',label:'禁忌与罪',type:'textarea'},{key:'miracle',label:'神迹 / 证据',type:'textarea'},{key:'doubt',label:'争议、异端与骗局',type:'textarea'},{key:'impact',label:'社会与剧情影响',type:'textarea'},commonFields.tags,commonFields.notes]},
 {key:'civilization',name:'文明与社会',icon:'♜',desc:'族群、制度、阶层、礼俗、婚姻、法律与日常',fields:[commonFields.title,commonFields.image,{key:'type',label:'条目类型',type:'select',options:['文明','国家','族群','阶层','制度','法律','礼俗','家庭结构','教育','节庆','其他']},{key:'values',label:'核心价值观',type:'textarea'},{key:'government',label:'权力与治理',type:'textarea'},{key:'classes',label:'阶层与流动',type:'textarea'},{key:'family',label:'家庭、婚姻与继承',type:'textarea'},{key:'law',label:'法律与惩罚',type:'textarea'},{key:'etiquette',label:'礼仪与禁忌',type:'textarea'},{key:'daily',label:'衣食住行',type:'textarea'},{key:'conflicts',label:'内部矛盾与偏见',type:'textarea'},{key:'outsiders',label:'如何看待外来者',type:'textarea'},commonFields.tags,commonFields.notes]},
 {key:'knowledge',name:'知识与技艺',icon:'⌘',desc:'科技、魔法研究、工艺、医学、教育与信息壁垒',fields:[commonFields.title,commonFields.image,{key:'field',label:'领域',type:'text'},{key:'level',label:'发展水平',type:'text'},{key:'principle',label:'原理',type:'textarea'},{key:'method',label:'制作 / 使用方法',type:'textarea'},{key:'tools',label:'工具与材料',type:'textarea'},{key:'masters',label:'掌握者 / 机构',type:'textarea'},{key:'access',label:'学习门槛',type:'textarea'},{key:'limits',label:'限制与风险',type:'textarea'},{key:'history',label:'发展史',type:'textarea'},{key:'impact',label:'对战争与生活的改变',type:'textarea'},commonFields.tags,commonFields.notes]},
 {key:'geography',name:'地理与环境',icon:'△',desc:'大陆、国家、城市、地貌、气候、资源与交通',fields:[commonFields.title,commonFields.image,{key:'type',label:'地理类型',type:'select',options:['大陆','国家','地区','城市','村镇','山脉','河流','海洋','遗迹','特殊空间','其他']},{key:'parent',label:'所属区域',type:'text'},{key:'coordinates',label:'地图坐标 / 方位',type:'text'},{key:'terrain',label:'地貌与气候',type:'textarea'},{key:'resources',label:'资源与物产',type:'textarea'},{key:'population',label:'人口与居民',type:'textarea'},{key:'transport',label:'交通与距离',type:'textarea'},{key:'danger',label:'危险与灾害',type:'textarea'},{key:'landmarks',label:'地标与景观',type:'textarea'},{key:'storyUse',label:'剧情功能',type:'textarea'},commonFields.tags,commonFields.notes]},
 {key:'items',name:'道具信物',icon:'◇',desc:'武器、遗物、钥匙、文件、交通工具与象征物',fields:[commonFields.title,commonFields.image,{key:'type',label:'类别',type:'text'},{key:'owner',label:'持有者 / 归属',type:'text'},{key:'origin',label:'来源与制造者',type:'textarea'},{key:'appearance',label:'外观与材质',type:'textarea'},{key:'function',label:'功能 / 能力',type:'textarea'},{key:'cost',label:'使用代价',type:'textarea'},{key:'limits',label:'限制与损坏条件',type:'textarea'},{key:'history',label:'流转历史',type:'textarea'},{key:'symbol',label:'象征意义',type:'textarea'},{key:'plot',label:'剧情作用 / 伏笔',type:'textarea'},commonFields.tags,commonFields.notes]},
 {key:'bonds',name:'羁绊恩怨',icon:'∞',desc:'承诺、债、救命之恩、血仇、误解与未完成之事',fields:[commonFields.title,{key:'parties',label:'相关人物 / 阵营',type:'text',required:true},{key:'kind',label:'羁绊类型',type:'select',options:['恩情','债务','承诺','血仇','背叛','误解','共同秘密','竞争','依赖','宿命','其他']},{key:'origin',label:'起因',type:'textarea'},{key:'debt',label:'欠下什么 / 想得到什么',type:'textarea'},{key:'public',label:'公开程度',type:'select',options:['公开','部分人知晓','绝密','本人也不清楚']},{key:'trigger',label:'触发 / 激化条件',type:'textarea'},{key:'resolution',label:'可能的偿还或和解',type:'textarea'},{key:'plot',label:'对应剧情节点',type:'textarea'},commonFields.tags,commonFields.notes]},
 {key:'plotLines',name:'剧情线',icon:'≋',desc:'主线、支线、感情线、悬疑线与伏笔回收',fields:[commonFields.title,{key:'type',label:'剧情线类型',type:'select',options:['主线','角色线','感情线','悬疑线','权谋线','冒险线','支线','伏笔线','其他']},{key:'status',label:'状态',type:'select',options:['构思','进行中','待回收','已完成','废弃']},{key:'order',label:'排序数字',type:'number'},{key:'goal',label:'目标 / 核心问题',type:'textarea'},{key:'start',label:'起点',type:'textarea'},{key:'beats',label:'关键节点',type:'textarea'},{key:'climax',label:'高潮',type:'textarea'},{key:'ending',label:'结局 / 回收',type:'textarea'},{key:'characters',label:'涉及角色',type:'textarea'},{key:'clues',label:'线索与伏笔',type:'textarea'},{key:'dependencies',label:'依赖的其他剧情线',type:'textarea'},commonFields.tags,commonFields.notes]},
 {key:'stories',name:'故事集',icon:'▧',desc:'传说、民间故事、番外、梦境、案例与场景灵感',fields:[commonFields.title,commonFields.image,{key:'type',label:'类型',type:'select',options:['传说','神话','童谣','民间故事','番外','梦境','回忆','场景灵感','短篇','其他']},{key:'speaker',label:'讲述者 / 视角',type:'text'},{key:'timePlace',label:'时间与地点',type:'text'},{key:'content',label:'故事内容',type:'textarea',required:true},{key:'truth',label:'真实版本 / 隐藏含义',type:'textarea'},{key:'function',label:'在正文中的作用',type:'textarea'},commonFields.tags,commonFields.notes]},
 {key:'manuscripts',name:'稿件库',icon:'✎',desc:'章节、场景与正文编辑，自动统计字数',special:'writing',fields:[commonFields.title]},
 {key:'communications',name:'通讯',icon:'✉',desc:'信件、聊天、广播、密令、公告与角色对话档案',fields:[commonFields.title,{key:'type',label:'通讯类型',type:'select',options:['书信','聊天','电报','广播','公告','密令','日记','留言','梦中通讯','其他']},{key:'sender',label:'发送者',type:'text'},{key:'receiver',label:'接收者',type:'text'},{key:'date',label:'时间',type:'text'},{key:'channel',label:'媒介 / 渠道',type:'text'},{key:'content',label:'内容',type:'textarea',required:true},{key:'subtext',label:'潜台词 / 暗号',type:'textarea'},{key:'intercepted',label:'是否被截获 / 误读',type:'textarea'},commonFields.tags,commonFields.notes]},
 {key:'reminders',name:'提醒',icon:'◷',desc:'待补设定、伏笔回收、写作计划与截止日期',fields:[commonFields.title,{key:'due',label:'提醒日期',type:'datetime-local'},{key:'priority',label:'优先级',type:'select',options:['低','普通','高','紧急']},{key:'status',label:'状态',type:'select',options:['待处理','进行中','已完成','搁置']},{key:'linked',label:'关联条目 / 章节',type:'text'},{key:'content',label:'任务说明',type:'textarea'},{key:'repeat',label:'重复规则（文字说明）',type:'text'},commonFields.tags,commonFields.notes]},
 {key:'statistics',name:'统计',icon:'▥',desc:'设定数量、字数、完成度、近期更新与薄弱板块',special:'stats',fields:[]},
 {key:'graphs',name:'图谱',icon:'⌬',desc:'自动汇总角色与组织关系，可拖动节点',special:'graph',fields:[]},
 {key:'languages',name:'文字',icon:'文',desc:'语言、文字、命名规则、词典、语法与称谓系统',fields:[commonFields.title,commonFields.image,{key:'type',label:'条目类型',type:'select',options:['语言','文字系统','方言','命名规则','词汇','称谓','暗号','诗歌格律','其他']},{key:'users',label:'使用者 / 地区',type:'text'},{key:'sounds',label:'发音与音系',type:'textarea'},{key:'script',label:'字形与书写方向',type:'textarea'},{key:'grammar',label:'语法特点',type:'textarea'},{key:'vocabulary',label:'核心词汇 / 例句',type:'textarea'},{key:'naming',label:'姓名与地名规则',type:'textarea'},{key:'register',label:'敬语、阶级与语域',type:'textarea'},{key:'history',label:'演变与借词',type:'textarea'},commonFields.tags,commonFields.notes]},
 {key:'calendar',name:'历法',icon:'▦',desc:'自定义纪元、月份、星期、季节、月相与节日',special:'calendar',fields:[commonFields.title,{key:'era',label:'纪元名称',type:'text'},{key:'yearLength',label:'一年天数',type:'number'},{key:'weekLength',label:'一周天数',type:'number'},{key:'months',label:'月份（每行：名称,天数）',type:'textarea',placeholder:'星芽月,30\n长昼月,31'},{key:'seasons',label:'季节与月份范围',type:'textarea'},{key:'moons',label:'月亮 / 天体周期',type:'textarea'},{key:'leap',label:'闰年规则',type:'textarea'},{key:'holidays',label:'节日（每行：月-日 名称）',type:'textarea'},commonFields.notes]},
 {key:'archiveAudit',name:'补档案',icon:'✓',desc:'检查空缺字段、孤立条目、待补内容与设定冲突',special:'audit',fields:[]}
];
const moduleMap=Object.fromEntries(MODULES.map(m=>[m.key,m]));
