'use strict';

function renderHome(){
 const p=activeProject();const total=MODULES.reduce((n,m)=>n+(p.modules[m.key]?.length||0),0);const words=p.modules.manuscripts.reduce((n,x)=>n+wordCount(x.content),0);const recent=allItems().sort((a,b)=>new Date(b.updatedAt||b.createdAt)-new Date(a.updatedAt||a.createdAt)).slice(0,4);
 const quick=['characters','worldBible','mapCenter','relationships','plotLines','manuscripts','reminders','archiveAudit'];
 return`<div class="page"><section class="hero"><h1>把你的世界，安静地放在这里。</h1><p>资料默认只保存在这台设备，不上传创作内容。地图、关系与正文可以离线编辑。</p><div class="hero-row"><button class="primary" data-open-module="worldBible">继续搭建</button><button class="secondary" data-action="install-help">添加到主屏幕</button></div><div class="stats-strip"><div class="stat-pill"><b>${total}</b><span>设定条目</span></div><div class="stat-pill"><b>${words.toLocaleString()}</b><span>正文字符</span></div><div class="stat-pill"><b>${p.modules.reminders.filter(x=>x.status!=='已完成').length}</b><span>待处理</span></div></div></section>
 <div class="section-head"><h2>常用入口</h2><button data-route="library">全部 28 个板块</button></div><div class="quick-grid">${quick.map(k=>{const m=moduleMap[k];return`<button class="quick-card" data-open-module="${k}"><i>${m.icon}</i><span>${m.name}</span></button>`}).join('')}</div>
 <div class="section-head"><h2>最近编辑</h2><button data-action="search">搜索全部</button></div>${recent.length?`<div class="list">${recent.map(renderListItem).join('')}</div>`:`<div class="card empty"><div class="empty-icon">✦</div><h3>从第一条设定开始</h3><p>建议先写“世界总纲”，再建立角色与核心矛盾。所有内容都会自动保存。</p><button class="primary" data-open-module="worldBible">新建世界总纲</button></div>`}</div>`;
}
function renderLibrary(){return`<div class="page"><div class="page-title"><div><h1>世界设定</h1><p>28 个板块可自由使用，不需要的板块可以暂时留空</p></div></div><div class="module-grid">${MODULES.map(m=>`<button class="card module-card" data-open-module="${m.key}"><small>${countFor(m.key)}</small><span class="module-icon">${m.icon}</span><b>${m.name}</b><p>${m.desc}</p></button>`).join('')}</div></div>`;}
function renderWritingHub(){const p=activeProject();const ms=p.modules.manuscripts;const stories=p.modules.stories;const plots=p.modules.plotLines;return`<div class="page"><div class="page-title"><div><h1>创作中心</h1><p>章节正文、剧情线与故事素材</p></div><button class="tiny-btn" data-action="new-manuscript">＋新章节</button></div><section class="hero"><h1>${ms.length?`${ms.length} 个稿件，共 ${ms.reduce((n,x)=>n+wordCount(x.content),0).toLocaleString()} 字`:'第一章，从一个画面开始'}</h1><p>稿件自动保存到本机。写完后请定期导出备份到 iCloud Drive。</p><div class="hero-row"><button class="primary" data-action="new-manuscript">开始写作</button><button class="secondary" data-action="export">导出备份</button></div></section><div class="section-head"><h2>稿件库</h2><button data-open-module="manuscripts">查看全部</button></div>${ms.length?`<div class="list">${ms.slice().sort(sortUpdated).slice(0,6).map(x=>renderListItem({...x,_module:'manuscripts'})).join('')}</div>`:'<div class="card empty"><div class="empty-icon">✎</div><h3>还没有正文</h3><p>新建章节后可全屏写作，自动显示字符数。</p></div>'}<div class="section-head"><h2>剧情与素材</h2></div><div class="quick-grid">${[['plotLines','剧情线',plots.length],['stories','故事集',stories.length],['communications','通讯',countFor('communications')],['characterJourney','角色历程',countFor('characterJourney')]].map(x=>`<button class="quick-card" data-open-module="${x[0]}"><i>${moduleMap[x[0]].icon}</i><span>${x[1]} · ${x[2]}</span></button>`).join('')}</div></div>`;}
function renderVisualHub(){return`<div class="page"><div class="page-title"><div><h1>可视化中心</h1><p>地图、关系图谱、时间线与历法</p></div></div><div class="module-grid"><button class="card module-card" data-open-module="mapCenter"><span class="module-icon">⌖</span><b>地图中心</b><p>上传底图，插入城市、山脉、森林、遗迹与自定义标记</p></button><button class="card module-card" data-open-module="graphs"><span class="module-icon">⌬</span><b>关系图谱</b><p>自动读取角色、组织和关系，可拖动整理节点</p></button><button class="card module-card" data-open-module="calendar"><span class="module-icon">▦</span><b>世界历法</b><p>建立纪元、月份、星期、季节、月相与节日</p></button><button class="card module-card" data-open-module="worldPlot"><span class="module-icon">✦</span><b>世界时间线</b><p>按纪元排列历史、灾难、战争与重大变化</p></button><button class="card module-card" data-open-module="characterJourney"><span class="module-icon">⌁</span><b>角色时间线</b><p>跟踪人物经历、选择、获得、失去与成长</p></button><button class="card module-card" data-open-module="statistics"><span class="module-icon">▥</span><b>设定统计</b><p>查看条目、字数、完成度与薄弱板块</p></button></div></div>`;}

function countFor(k){return activeProject().modules[k]?.length||0;}
function allItems(){const p=activeProject();return MODULES.flatMap(m=>(p.modules[m.key]||[]).map(x=>({...x,_module:m.key})));}
function sortUpdated(a,b){return new Date(b.updatedAt||b.createdAt)-new Date(a.updatedAt||a.createdAt);}
function itemSubtitle(item,m){return item.summary||item.role||item.type||item.character||item.source&&item.target&&`${item.source} → ${item.target}`||item.content?.slice(0,52)||m.desc;}
function renderListItem(item){const m=moduleMap[item._module]||moduleMap[currentModule];const tags=parseTags(item.tags).slice(0,3);return`<button class="card list-item" data-item="${esc(item.id)}" data-module="${m.key}">${item.image?`<img class="thumb" src="${item.image}" alt="">`:`<span class="thumb">${m.icon}</span>`}<span class="list-main"><b>${esc(item.title||'未命名')}</b><p>${esc(itemSubtitle(item,m))}</p>${tags.length?`<span class="chip-row">${tags.map(t=>`<i class="chip">${esc(t)}</i>`).join('')}</span>`:''}</span><span class="chev">›</span></button>`;}
function parseTags(v){if(Array.isArray(v))return v;return String(v||'').split(/[，,、\n]/).map(x=>x.trim()).filter(Boolean);}

function openModule(key){const m=moduleMap[key];currentModule=key;currentItem=null;if(m.special==='map')route='map';else if(m.special==='graph')route='graph';else if(m.special==='calendar')route='calendar';else if(m.special==='stats')route='stats';else if(m.special==='audit')route='audit';else if(m.special==='writing')route='module';else route='module';render();}
function renderModulePage(key){const m=moduleMap[key];const items=activeProject().modules[key].slice().sort((a,b)=>m.timeline?(Number(a.order||9999)-Number(b.order||9999)):sortUpdated(a,b));return`<div class="page"><div class="page-title"><button class="back-btn" data-route="library">‹</button><div><h1>${m.icon} ${m.name}</h1><p>${m.desc}</p></div><button class="tiny-btn" data-action="add-item">＋ 新建</button></div><div class="searchbar"><input id="moduleSearch" placeholder="搜索${m.name}…"><button class="filter-btn" data-action="add-item">＋</button></div><div id="moduleList">${items.length?(m.timeline?renderTimeline(items,m):`<div class="list">${items.map(x=>renderListItem({...x,_module:key})).join('')}</div>`):renderEmpty(m)}</div></div>`;}
function renderEmpty(m){return`<div class="card empty"><div class="empty-icon">${m.icon}</div><h3>还没有${m.name}</h3><p>${m.desc}。点击下方按钮创建第一条档案。</p><button class="primary" data-action="add-item">新建${m.name}</button></div>`;}
function renderTimeline(items,m){return`<div class="timeline">${items.map(x=>`<button class="card time-item" data-item="${x.id}" data-module="${m.key}"><small>${esc(x.date||x.era||`顺序 ${x.order||'未定'}`)}</small><h3>${esc(x.title||'未命名事件')}</h3><p>${esc(x.event||x.process||x.summary||m.desc)}</p></button>`).join('')}</div>`;}
function renderDetail(key,id){const m=moduleMap[key];const item=activeProject().modules[key].find(x=>x.id===id);if(!item){route='module';return renderModulePage(key);}const rows=m.fields.filter(f=>!['title','image','tags'].includes(f.key)&&item[f.key]).map(f=>`<div class="detail-row"><span>${esc(f.label)}</span><div>${esc(item[f.key])}</div></div>`).join('');return`<div class="page"><div class="page-title"><button class="back-btn" data-open-module="${key}">‹</button><div><h1>${m.name}</h1><p>最后编辑 ${fmtDate(item.updatedAt)}</p></div><button class="tiny-btn" data-action="edit-item">编辑</button></div><div class="detail-cover">${item.image?`<img src="${item.image}" alt="">`:`<div class="cover-letter">${esc((item.title||m.name)[0])}</div>`}</div><div class="detail-head"><h2>${esc(item.title||'未命名')}</h2><p>${esc(item.summary||item.alias||item.type||m.desc)}</p></div>${parseTags(item.tags).length?`<div class="chip-row">${parseTags(item.tags).map(t=>`<i class="chip">${esc(t)}</i>`).join('')}</div>`:''}<section class="card detail-section"><h3>档案内容</h3>${rows||'<p style="color:var(--muted);font-size:13px">暂未填写详细内容。</p>'}</section><div class="hero-row" style="margin-top:12px"><button class="secondary" data-action="duplicate-item">复制档案</button><button class="danger-btn" data-action="delete-item">删除</button></div></div>`;}
